[package]
name = "intermezzos"
version = "0.1.0"
authors = ["Steve Klabnik <steve@steveklabnik.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
bytestool = "0.2.0"
sizedbytes = "0.1.0"

[profile.release]
panic = "abort"
